# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='negative_votes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='positive_votes',
        ),
    ]
