# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_auto_20170813_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user_id',
        ),
    ]
