# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_auto_20170813_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.User'),
        ),
    ]
