# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0010_auto_20170813_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.User')),
            ],
        ),
    ]
