# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_auto_20170813_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
