# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0013_auto_20170813_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVoteQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upvoteques',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question'),
        ),
        migrations.AddField(
            model_name='upvoteques',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.User'),
        ),
    ]
