# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0015_auto_20170814_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addstar',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question'),
        ),
        migrations.AddField(
            model_name='addstar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.User'),
        ),
    ]
