# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0016_auto_20170814_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownVoteAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvote_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.User')),
            ],
        ),
        migrations.CreateModel(
            name='UpVoteAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.User')),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='negative_votes',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='positive_votes',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='total_points',
            new_name='upvotes',
        ),
    ]
