# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0017_auto_20170814_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvoteans',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Answer'),
        ),
        migrations.AlterField(
            model_name='upvoteans',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Answer'),
        ),
    ]
