# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0018_auto_20170814_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvoteans',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question'),
        ),
        migrations.AddField(
            model_name='upvoteans',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Question'),
        ),
    ]
