# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0019_auto_20170826_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
